---
title: "1 Look at data"
author: ""
date: "Last updated in `r format(Sys.time(), '%B %Y')`"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	comment = "",
	dpi = 300
)
```

```{r preface}
# Packages
library(tidyverse) # Wrangle and visualise data
library(knitr)     # Tidy output
library(here)      # Navigate files

# Plot setup
theme_set(theme_bw())
theme_update(
  aspect.ratio = 1,
  panel.grid.minor = element_blank(),
  plot.title = element_text(hjust = 0.5),
  plot.subtitle = element_text(hjust = 0.5),
  legend.position = "none"
)
```

## 1.1 Why look at data?

```{r raw-data}
# Inspect the data (the raw data are readily available from R)
kable(anscombe)
```

```{r wrangle-data}
# Wrangle data
anscombe_cleaned <- anscombe %>% 
  # Add unique identifier per observation
  mutate(id = rownames(anscombe)) %>% 
  
  # Wide to long format
  pivot_longer(cols = c(starts_with("x"), starts_with("y")),
               names_to = "variable",
               values_to = "value") %>% 
  
  # Text parsing
  transmute(
    id = id,
    plot = str_sub(string = variable, start = 2, end = 2),
    axis = str_sub(string = variable, start = 1, end = 1),
    value = value
  ) %>% 
  
  # Long to wide format
  pivot_wider(names_from = axis, values_from = value)

# Inspect the cleaned data
kable(anscombe_cleaned)

# Save the cleaned and raw datasets
write_rds(anscombe_cleaned, path = here("data", "anscombe_cleaned.rds"))
write_rds(anscombe, path = here("data", "anscombe_raw.rds"))
```

```{r reproduce-plots, fig.height = 5, fig.width = 5}
# Reproduce plots, with slight modification
anscombe_cleaned %>% 
  ggplot(aes(x = x, y = y)) +
    geom_point() +
    geom_smooth(formula = "y ~ x", method = "lm", se = FALSE, colour = "blue3") +
    facet_wrap(~plot) +
    labs(x = "x values",
         y = "y values",
         caption = "Figure 1.1",
         title = "\nPlots of Anscombe's quartet",
         subtitle = "All have a correlation coefficient of 0.81")

# Save the resulting graphic
ggsave(filename = "figure-1.1.png",
       path = here("graphics"))
```

## Appendix

```{r appendix}
sessionInfo()
```
